const groceries = [
  { id: 1, name: "Frutilla", unitPrice: 50.3, category: "Frutas" },
  { id: 2, name: "Uva", unitPrice: 23.0, category: "Frutas" },
  { id: 3, name: "Naranja", unitPrice: 76.0, category: "Frutas" },
  { id: 4, name: "Banana", unitPrice: 55.9, category: "Frutas" },
  { id: 5, name: "Manzana", unitPrice: 31.0, category: "Frutas" },
  { id: 6, name: "Zanahoria", unitPrice: 17.6, category: "Verduras" },
  { id: 7, name: "Puerro", unitPrice: 30.0, category: "Verduras" },
  { id: 8, name: "Champiñon", unitPrice: 80.0, category: "Verduras" },
  { id: 9, name: "Pan", unitPrice: 22.5, category: "Panadería" },
  { id: 10, name: "Huevo", unitPrice: 29.0, category: "Lácteos" },
  { id: 11, name: "Queso", unitPrice: 130.0, category: "Lácteos" },
  { id: 12, name: "Manteca", unitPrice: 90.0, category: "Lácteos" },
  { id: 13, name: "Pollo", unitPrice: 115.0, category: "Carnes" },
  { id: 14, name: "Milanesa", unitPrice: 97.0, category: "Carnes" },
  { id: 15, name: "Helado", unitPrice: 88.0, category: "Postres" },
  { id: 16, name: "Pescado", unitPrice: 150.0, category: "Carnes" },
  { id: 17, name: "Arroz", unitPrice: 36.0, category: "Otros" },
  { id: 18, name: "Fideos", unitPrice: 56.0, category: "Otros" },
  { id: 19, name: "Bizcocho", unitPrice: 72.0, category: "Panadería" },
  { id: 20, name: "Papel Higiénico", unitPrice: 45.0, category: "Otros" },
  { id: 21, name: "Alcohol en Gel", unitPrice: 83.0, category: "Otros" },
];

export default groceries;
